'use client'
import { useMemo, useState } from 'react'

const guides=[
  {provider:'AWS',code:'SAA-C03',title:'Solutions Architect',level:'Associate',pages:286,price:29,color:'#ffb84d'},
  {provider:'AZURE',code:'AZ-104',title:'Azure Administrator',level:'Associate',pages:252,price:27,color:'#58a6ff'},
  {provider:'GCP',code:'PCA',title:'Cloud Architect',level:'Professional',pages:318,price:32,color:'#60e8ad'},
  {provider:'AWS',code:'SCS-C02',title:'Security Specialty',level:'Specialty',pages:234,price:31,color:'#ffb84d'},
  {provider:'AZURE',code:'AZ-900',title:'Azure Fundamentals',level:'Foundational',pages:148,price:19,color:'#58a6ff'},
  {provider:'GCP',code:'ACE',title:'Associate Cloud Engineer',level:'Associate',pages:221,price:25,color:'#60e8ad'}
]

function Cover({g,big=false}){return <div className={'cover '+(big?'big':'')} style={{'--accent':g.color}}><div className="coverTop"><b>cloudbound<span>.</span></b><small>2026 EDITION</small></div><div className="cloud">☁</div><small>{g.provider} CERTIFICATION</small><strong>{g.title}</strong><code>{g.code} · STUDY GUIDE</code></div>}

export default function Home(){
 const [filter,setFilter]=useState('ALL');const [cart,setCart]=useState([]);const [drawer,setDrawer]=useState(false);const shown=useMemo(()=>filter==='ALL'?guides:guides.filter(g=>g.provider===filter),[filter]);const total=cart.reduce((n,g)=>n+g.price,0)
 return <main>
  <div className="topbar"><span>✦ FREE 2026 EXAM UPDATES</span><span>INSTANT PDF + EPUB DOWNLOAD</span><span>7-DAY PASS GUARANTEE</span></div>
  <nav><a className="logo">cloudbound<span>.</span></a><div><a href="#guides">GUIDES</a><a href="#bundle">BUNDLES</a><a href="#method">OUR METHOD</a></div><button onClick={()=>setDrawer(true)}>YOUR STACK <b>{cart.length}</b></button></nav>
  <section className="hero"><div className="heroCopy"><p className="label">— BUILT FOR THE EXAM. USEFUL AFTER IT.</p><h1>Learn the cloud.<br/><em>Own the exam.</em></h1><p className="lede">Practical, visual study guides for cloud engineers who want understanding—not another 40-hour video playlist.</p><div className="actions"><a href="#guides">EXPLORE THE GUIDES ↗</a><a href="#method">SEE HOW WE TEACH →</a></div><div className="rating"><span>JN</span><span>AK</span><span>ML</span><p><b>4.9 / 5</b><small>FROM 2,400+ CLOUD LEARNERS</small></p></div></div><div className="heroArt"><div className="ring r1"/><div className="ring r2"/><Cover g={guides[0]} big/><div className="pass"><small>PASS RATE</small><b>92%</b><small>OF SURVEYED READERS</small></div></div></section>
  <div className="marquee">NO FLUFF　✦　REAL ARCHITECTURE　✦　EXAM-ALIGNED　✦　LIFETIME UPDATES　✦　NO FLUFF</div>
  <section className="catalog" id="guides"><header><div><p className="label">// THE LIBRARY</p><h2>Pick your next<br/>certification.</h2></div><p>Each guide turns an overwhelming exam blueprint into a focused, memorable path—with diagrams, drills, and decision frameworks.</p></header><div className="filters">{['ALL','AWS','AZURE','GCP'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f==='ALL'?'ALL GUIDES':f}</button>)}</div><div className="grid">{shown.map((g,i)=><article key={g.code}><span className="num">0{i+1}</span><Cover g={g}/><p className="provider" style={{color:g.color}}>{g.provider} · {g.level.toUpperCase()}</p><h3>{g.title}</h3><p className="desc">Clear architecture maps, decision tables, exam traps, and scenario drills for confident test-day choices.</p><div className="spec"><span>{g.pages} PAGES</span><span>PDF + EPUB</span><span>2026</span></div><div className="buy"><strong>${g.price}</strong><button onClick={()=>setCart([...cart,g])}>ADD TO STACK ＋</button></div></article>)}</div></section>
  <section className="bundle" id="bundle"><div><p className="label">// THE MULTI-CLOUD BUNDLE</p><h2>Three clouds.<br/>One serious edge.</h2><p>Our flagship associate guides for AWS, Azure, and Google Cloud—plus a cross-cloud services map.</p><ul><li>AWS SAA-C03 complete guide</li><li>Azure AZ-104 complete guide</li><li>Google Cloud ACE complete guide</li><li>Cross-cloud services cheat sheet</li></ul><div className="bundleBuy"><strong><del>$81</del> $59</strong><button onClick={()=>{setCart([guides[0],guides[1],guides[5]]);setDrawer(true)}}>GET THE BUNDLE ↗</button></div></div><div className="stack"><div><Cover g={guides[0]}/></div><div><Cover g={guides[1]}/></div><div><Cover g={guides[5]}/></div></div></section>
  <section className="method" id="method"><p className="label">// WHY CLOUDBOUND</p><h2>Designed for how<br/>technical minds learn.</h2><div>{[['01','SEE THE SYSTEM','Architecture maps connect services before details bury the story.'],['02','MAKE THE CALL','Decision tables teach when to choose a service—not just what it does.'],['03','TEST THE MODEL','Scenario drills explain why every wrong answer is wrong.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="quote"><blockquote>“I stopped memorizing service names and started seeing the architecture. Passed SAA-C03 with 812.”</blockquote><p><b>RINA S.</b><small>PLATFORM ENGINEER · TORONTO</small></p></section>
  <section className="cta"><p className="label">YOUR NEXT ROLE IS WAITING</p><h2>Study smarter.<br/><em>Ship sooner.</em></h2><a href="#guides">FIND YOUR GUIDE ↗</a></section>
  <footer><a className="logo">cloudbound<span>.</span></a><p>FIELD GUIDES FOR THE CLOUD-CURIOUS.</p><small>© 2026 CLOUDBOUND PRESS</small></footer>
  {drawer&&<><div className="scrim" onClick={()=>setDrawer(false)}/><aside><button className="close" onClick={()=>setDrawer(false)}>×</button><p className="label">// YOUR STACK</p><h2>Ready to level up?</h2>{cart.length?<> <div className="cart">{cart.map((g,i)=><div key={i}><i style={{background:g.color}}>{g.code}</i><p><b>{g.title}</b><small>PDF + EPUB</small></p><strong>${g.price}</strong><button onClick={()=>setCart(cart.filter((_,j)=>j!==i))}>×</button></div>)}</div><div className="total"><span>TOTAL</span><b>${total}</b></div><button className="checkout" onClick={()=>alert('Demo checkout — connect Stripe to begin selling.')}>CHECKOUT SECURELY ↗</button></>:<p>Your stack is empty. Pick a guide and start building.</p>}</aside></>}
 </main>
}
